# Generated by Django 5.1.1 on 2024-10-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_event_photo_event_banner_event_more_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='form_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
