# Generated by Django 5.1.1 on 2024-10-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_formconfig_form_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formconfig',
            name='form_id',
        ),
    ]
