# Generated by Django 5.1.1 on 2024-10-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_remove_formconfig_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formconfig',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
