# Generated by Django 5.1.1 on 2024-10-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_alter_formconfig_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='formconfig',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
