# Generated by Django 5.1.1 on 2024-10-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
