# Generated by Django 5.1.1 on 2024-10-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_3',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
