# Generated by Django 5.1.1 on 2024-10-07 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_ticket_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_3',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.event'),
        ),
    ]
