# Generated by Django 5.1.1 on 2024-10-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_ticket_3_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_3',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
